version: '3.9'

#run this command first (to fix nextjs building cache issue)
#docker-compose up -d backend
#then run 
#docker-compose up -d frontend

services:
 backend:
  container_name: backend
  image: backend
  build:
   context: ./server
   dockerfile: Dockerfile
   network : host
  network_mode : host
  user: root
  ports:
   - 8080:8080
  restart: always
   
 frontend:
  container_name: frontend
  image: frontend
  build:
   context: ./client
   dockerfile: Dockerfile
   network : host
  network_mode : host
  user: root
  ports:
   - 80:80
  restart: always
  depends_on:
      - backend
