version: '3.9'

services:
 backend:
  container_name: backend
  image: backend
  build:
   context: ./server
   dockerfile: Dockerfile
  ports:
   - 8080:8080
  restart: always
   
 frontend:
  container_name: frontend
  image: frontend
  build:
   context: ./client
   dockerfile: Dockerfile
  ports:
   - 3000:3000
  restart: always
  depends_on:
   - backend

# networks:
#  app-network:
#   driver: bridge